import type { Travel } from "@/content/types"

export const travels: readonly Travel[] = [
  {
    slug: "boston-2023",
    title: { fr: "Premier voyage aux Etats-Unis" },
    subtitle: { fr: "Boston, Etats-Unis" },
    summary: { fr: "Major de Rocket League." },
    description: { fr: "Première fois aux Etats-Unis, pour supporter mon frère et son équipe de Rocket League, participant au 3e major de cette saison, un tournoi international très important. Arrivée le 3 juillet, nous avons vécu la fête nationale, le 4 juillet, au bord de la rivière avec plusieurs personnes de son équipe. Au cours de cette semaine, avec ma maman et la maman d'un autre joueur, nous avons visité la ville et ses alentours, fait du shopping, découvert la vie américaine, et testé de nouvelles choses (commes les magasins américains). Cette semaine s'est suivie d'une victoire de son équipe, en remportant son premier tournoi physique en 3 mois." },
    country: "US",
    period: { start: "2023-07-03", end: "2023-07-10" },
    cover: "/media/travels/boston-2023/boston.jpeg",
    images: [],
  },
  {
    slug: "dusseldorf-2023",
    title: { fr: "Deuxième voyage en Allemagne" },
    subtitle: { fr: "Dusseldorf, Allemagne" },
    summary: { fr: "Championnat du monde de Rocket League." },
    description: { fr: "De retour en Allemagne, mais cette fois pour le plus grand événement de l'année, rassemblant des milliers de fans sur place et en ligne. Les championnants du monde, se déroulant 1 mois après le précédent tournoi international, se voit encore une fois remporté par la Team Vitality, dont mon frère fait partie, en remportant la finale 4 à 0, contre les détendeur du titre de l'année 2022."},
    country: "DE",
    period: { start: "2023-08-09", end: "2023-08-14" },
    cover: "/media/travels/dusseldorf-2023/dusseldorf.jpg",
    images: [],
  },
  {
    slug: "coppenhagen-2024",
    title: { fr: "Première visite en Danemark" },
    subtitle: { fr: "Copenhague, Danemark" },
    summary: { fr: "Major de Rocket League." },
    description: { fr: "Après une semaine de BTS Blanc, on part pour Copenhague, afin de commencer une nouvelle saison et cette fois à Copenhague, au Danemark. Toujours avec la même équipe, après leur titre de champion du monde, on repart pour une année. Copenhague fait partie de la plus belle ville que j'ai visité jusque là, où les gens sont très sympathiques, les quartiers très beaux et intéressants à visiter."},
    country: "DK",
    period: { start: "2024-03-28", end: "2024-04-01" },
    cover: "/media/travels/copenhagen-2024/copenhagen.jpg",
    images: [],
  },
  {
    slug: "london-2024",
    title: { fr: "Première visite en Angleterre" },
    subtitle: { fr: "Londres, Angleterre" },
    summary: { fr: "Major de Rocket League" },
    description: { fr: "On se retrouve, pour la deuxième partie de la saison, à Londres, une ville différente de celles qu'on a visité jusqu'ici, conduisant à l'inverse de ce qu'on a l'habitude de voir. Mais la ville, dans sa globalité, était très belle, avec le palace, le pont, ou le Big Ben."},
    country: "GB",
    period: { start: "2024-06-17", end: "2024-06-24" },
    cover: "/media/travels/london-2024/london.jpg",
    images: [],
  },
  {
    slug: "dallas-2024",
    title: { fr: "Deuxième fois aux Etats-Unis" },
    subtitle: { fr: "Dallas, Etats-Unis" },
    summary: { fr: "Championnat du monde de Rocket League." },
    description: { fr: "Après une saison mitigé, on se trouve aux Etats-Unis, pour les championnats du monde de Rocket League, et pour la deuxième en 2 ans, à Dallas. J'étais très heureux à l'idée d'aller là-bas, ayant entendu pas mal de bons retours sur la ville. Après avoir visité le Forth Worth Botanic Garden, nous avons découvert le ranch de la fameuse série Dallas."},
    country: "US",
    period: { start: "2024-09-09", end: "2024-09-16" },
    cover: "/media/travels/dallas-2024/dallas.jpg",
    images: [],
  },
  {
    slug: "birmingham-2025",
    title: { fr: "Deuxième voyage en Angleterre" },
    subtitle: { fr: "Birmingham, Angleterre" },
    summary: { fr: "Major de Rocket League." },
    description: { fr: "Nouvelle saison, nouvelle équipe, et nouvelle fois en Angleterre, cette fois à Birmingham. Pas grand chose à dire sur cette ville, étant donné que j'ai pas trop aimé : rien à visiter, vide de contenu, ou de beaux paysages, mais comme on dit, on était là avant tout pour un événement."},
    country: "GB",
    period: { start: "2025-03-26", end: "2025-03-31" },
    cover: "/media/travels/birmingham-2025/birmingham.jpg",
    images: [],
  },
  {
    slug: "raleigh-2025",
    title: { fr: "Troisième fois aux Etats-Unis" },
    subtitle: { fr: "Raleigh, Etats-Unis" },
    summary: { fr: "Major de Rocket League." },
    description: { fr: "Ce voyage se divise en plusieurs : le premier, voyage à Raleigh pour la même raison que les précédentes fois, on nous sommes allés entre ami, avec des amis américains rencontré lors de notre premier voyage à Boston en 2023. Nous étions dans un quartier agréable, très américain, et très calme. La ville avec des buildings et où nous avons visité le Musée des sciences naturelles de Caroline du Nord, qui était vraiment très intéressant. A la suite de ce premier voyage, pas de retour en France, mais direction Boston, où je vais passer 1 semaine chez mes amis américains, sur un bateau pour fêter la fête du 4 juillet."},
    country: "DE",
    period: { start: "2025-06-23", end: "2025-07-05" },
    cover: "/media/travels/raleigh-2025/raleigh.jpg",
    images: [],
  },
  {
    slug: "lyon-2025",
    title: { fr: "Week-end à Lyon" },
    subtitle: { fr: "Lyon, France" },
    summary: { fr: "Championnat du monde de Rocket League." },
    description: { fr: "Petit week-end de 3 jours, pour les championnants du monde de Rocket League. Cette fois-ci, nous avons pas tant visité la ville, mais sommes plutôt aller dans les alentours de l'arêne où a eu lieu l'événement, dans lequel 20.000 personnes se retrouvés pour mettre de l'ambiance ce week-end."},
    country: "FR",
    period: { start: "2025-09-12", end: "2025-09-15" },
    cover: "/media/travels/lyon-2025//lyon.jpg",
    images: [],
  },
  {
    slug: "boston-2026",
    title: { fr: "Quatrième voyage aux Etats-Unis" },
    subtitle: { fr: "Boston, Etats-Unis" },
    summary: { fr: "Major de Rocket League." },
    description: { fr: "Début de la nouvelle saison, avec une nouvelle équipe, et une nouvelle volonté de gagner un maximum de tournoi. Ambiance un peu plus hivernale, avec des tombées de neige, mais surtout une énorme tempête en approche menacant de retarder de plusieurs jours les départs d'avions, où je suis rentré plus tôt que mes billets. Cependant, très belle semaine en compagnie de ma famille américaine avec qui j'ai passé de très bons moments, et où mon frère a terminé à la 2e place sur ce tournoi."},
    country: "US",
    period: { start: "2026-02-16", end: "2026-02-22" },
    cover: "/media/travels/boston-2026/boston.jpeg",
    images: [],
  },
  {
    slug: "paris-2026",
    title: { fr: "Week-end à Paris" },
    subtitle: { fr: "Paris, France" },
    summary: { fr: "Major de Rocket League." },
    description: { fr: "De retour en France, après le dernier tournoi des mois en arrière, cette fois à la Défense Arene, où plus de 25.000 spectateurs sont attendus dans la plus grande salle jamais organisée dans l'histoire de Rocket League. Evidemment, pas beaucoup de visite de la ville, étant souvent à Paris et connaissant le coin, il était privilégié de rencontrer du monde. Malgré une 4e place, c'est une équipe française qui a remportée le trophée à la maison."},
    country: "FR",
    period: { start: "2026-05-22", end: "2026-05-25" },
    cover: "/media/travels/paris-2026/paris.jpg",
    images: [
      { src: "/images/travels/paris.jpg", alt: { fr: "Image de la ville de Paris"} },
      { src: "/images/travels/paris.jpg", alt: { fr: "Image de la ville de Paris"} },
    ],
  },
]